version: '3.7'
 
services:
    apache2:
        container_name: ${COMPOSE_PROJECT_NAME}_apache
        build:
            context: ./apache
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
                - APP_DOMAIN=${COMPOSE_PROJECT_NAME}${TLD_DOMAIN}
                - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER} 
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        networks:
            - frontend
            - backend
        expose:
          - "80"
          - "443"
        environment:
            - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}${TLD_DOMAIN}
            - CERT_NAME=shared
            - HTTPS_METHOD=noredirect
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
        depends_on:
            - php-fpm
            - mysql
    php-fpm:
      container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
      build:
        context: ./php-fpm
        args:
            - TAG_PHP_FPM=${TAG_PHP_FPM}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      networks:
        frontend:
        backend:
          aliases:
            - php
    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        build:
            context: ./mysql
            args:
                - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
                - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
        volumes:
            - ./var/data/mysql/database:/var/lib/mysql
        networks:
          backend:
            aliases:
              - mysqlhost
        environment:
            - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
            - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ROOT_HOST=%
    workspace:
        container_name: ${COMPOSE_PROJECT_NAME}_workspace
        build:
            context: ./workspace
            args:
              - TAG_WORKSPACE=${TAG_WORKSPACE} 
              - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
              - APP_DOMAIN=${COMPOSE_PROJECT_NAME}${TLD_DOMAIN}
        networks:
          - backend
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - x-service-shared:/etc/shared/x-service-shared
    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        build: ./phpmyadmin
        environment:
            - VIRTUAL_HOST=pma.${COMPOSE_PROJECT_NAME}${TLD_DOMAIN}
            - PMA_HOST=mysqlhost
            - PMA_USER=root
            - PMA_PASSWORD=pass
        networks:
            - frontend
            - backend
volumes:
  x-service-shared:
    external: true
networks:
    frontend:
        external:
            name: nginx-proxy
    backend:
        driver: bridge
